### PR TITLE
Fix running on slave issue

### PR DESCRIPTION
**Pull request by dcuenot**
Hello,

When the deploiement start on slave node, a transfer to the master is done before.
But I had this following issue:

```
[Deploy Sandbox] INFO: Transferring from /var/lib/jenkins/jenkins-slave/workspace/back-campaign-api_develop-ZFZJAPBHDCATZ4YGGKMQ7EKMGR2MKJXHSXDGTHZHMMUQ3YMM2DDA/target/campaign-api-0.0.1-SNAPSHOT.jar to /tmp/appDir5675522340862188965


[Deploy Sandbox] java.io.FileNotFoundException: /tmp/appDir5675522340862188965/campaign-api-0.0.1-SNAPSHOT.jar/target/campaign-api-0.0.1-SNAPSHOT.jar (Not a directory)
```

This PR is a proposal to solve this issue.
HTH

### CODE REVIEW

**Comment by dcuenot** [comment]
Thanks for the merge!
Do you know when will be the next release?

**Comment by nota-ja** [comment]
Our team has stambled over this bug, too.

Would you let us know when to release the next version, Team?

**Comment by dcuenot** [comment]
@WGautier or @olamy do you know when will be the next release?

**Comment by olamy** [comment]
release done

**Comment by nota-ja** [comment]
Thanks for the Team!

**Pull request merged**
